import React from "react";
import { Button, Table, Form } from "react-bootstrap";

const InvoicePrintPreview = () => {
  const dummyInvoice = {
    invoiceId: "INV-2025-00014",
    invoiceDate: "2025-06-05",
    dueDate: "2025-06-12",
    status: "Paid",
    seller: {
      name: "BBSCART Online Shopping",
      gstin: "29ABCDE1234F2Z5",
      address: "No.7, Bharathi Street, Puducherry",
      email: "info@bbscart.com",
      phone: "0413 291 5916",
    },
    buyer: {
      name: "John Doe",
      gstin: "33AAAAA1234A1Z5",
      address: "456 Buyer Road, Chennai",
      email: "john@example.com",
      phone: "9876543210",
    },
    items: [
      {
        name: "Gold Ring",
        code: "GR001",
        hsn: "7113",
        desc: "22K Hallmarked",
        qty: 1,
        price: 15000,
        discount: 0,
        cgst: 3,
        sgst: 3,
        igst: 0,
      },
    ],
    subtotal: 15000,
    tax: 900,
    total: 15900,
    paymentMode: "Wallet (Golddex)",
    escrow: "Released",
    walletTxnId: "WLT-90210-BBSCART",
    partial: {
      paid: 15900,
      due: 0,
    },
    notes: "Thanks for your purchase. Invoice auto-generated by CRM.",
    legal: "This is a computer-generated invoice. No signature required.",
  };

  return (
    <div className="container my-4 border p-4 bg-white">
      <h3 className="text-center mb-4">Invoice Preview</h3>

      <div className="d-flex justify-content-between">
        <div>
          <h5>Seller:</h5>
          <p>
            {dummyInvoice.seller.name}
            <br />
            {dummyInvoice.seller.address}
            <br />
            GSTIN: {dummyInvoice.seller.gstin}
            <br />
            Email: {dummyInvoice.seller.email}
            <br />
            Phone: {dummyInvoice.seller.phone}
          </p>
        </div>
        <div className="text-end">
          <h5>Invoice #: {dummyInvoice.invoiceId}</h5>
          <p>
            Date: {dummyInvoice.invoiceDate}
            <br />
            Due: {dummyInvoice.dueDate}
            <br />
            Status: <strong>{dummyInvoice.status}</strong>
          </p>
        </div>
      </div>

      <hr />

      <h5>Buyer:</h5>
      <p>
        {dummyInvoice.buyer.name}
        <br />
        {dummyInvoice.buyer.address}
        <br />
        GSTIN: {dummyInvoice.buyer.gstin}
        <br />
        Email: {dummyInvoice.buyer.email}
        <br />
        Phone: {dummyInvoice.buyer.phone}
      </p>

      <Table bordered responsive>
        <thead className="table-light">
          <tr>
            <th>#</th>
            <th>Item</th>
            <th>HSN/SAC</th>
            <th>Description</th>
            <th>Qty</th>
            <th>Rate</th>
            <th>Discount</th>
            <th>CGST%</th>
            <th>SGST%</th>
            <th>IGST%</th>
            <th>Total</th>
          </tr>
        </thead>
        <tbody>
          {dummyInvoice.items.map((item, index) => {
            const taxTotal =
              (item.price * (item.cgst + item.sgst + item.igst)) / 100;
            const total = item.price + taxTotal;
            return (
              <tr key={index}>
                <td>{index + 1}</td>
                <td>{item.name}</td>
                <td>{item.hsn}</td>
                <td>{item.desc}</td>
                <td>{item.qty}</td>
                <td>₹{item.price}</td>
                <td>₹{item.discount}</td>
                <td>{item.cgst}%</td>
                <td>{item.sgst}%</td>
                <td>{item.igst}%</td>
                <td>₹{total}</td>
              </tr>
            );
          })}
        </tbody>
      </Table>

      <div className="text-end">
        <p>Subtotal: ₹{dummyInvoice.subtotal}</p>
        <p>GST Tax: ₹{dummyInvoice.tax}</p>
        <p>
          <strong>Total: ₹{dummyInvoice.total}</strong>
        </p>
        <p>Payment Mode: {dummyInvoice.paymentMode}</p>
        <p>Escrow Status: {dummyInvoice.escrow}</p>
        <p>Wallet Txn ID: {dummyInvoice.walletTxnId}</p>
        <p>
          Paid: ₹{dummyInvoice.partial.paid} | Due: ₹{dummyInvoice.partial.due}
        </p>
      </div>

      <Form.Group className="mt-3">
        <Form.Label>Notes:</Form.Label>
        <Form.Control as="textarea" value={dummyInvoice.notes} readOnly />
      </Form.Group>

      <p className="mt-4">{dummyInvoice.legal}</p>

      <div className="d-flex gap-2 justify-content-end mt-3">
        <Button variant="outline-primary">Download PDF</Button>
        <Button variant="outline-success">Print</Button>
        <Button variant="outline-secondary">Send to Customer</Button>
        <Button variant="outline-dark">Back to List</Button>
      </div>
    </div>
  );
};

export default InvoicePrintPreview;
